config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root "tops#index"
  resources :posts, only: [:new, :create, :show] do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :caption, presence: true
  accepts_nested_attributes_for :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :likes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 20 }

  def update_without_current_password(params, *options)
    
    if params[:password].blank? && params[:password_confirmation].blank? 
      params.delete(:password)
      params.delete(:password_confirmation)
    end
      
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def liked_by(post_id)
    Like.find_by(user_id: id, post_id: post_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    @like.save
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    @like.destroy
  end

  private
    def like_params
      params.permit(:post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @post = Post.new
    @post.photos.build
  end

  def create
    @post = Post.new(post_params)
    if @post.photos.present?
      @post.save
      flash[:notice] = "投稿しました。"
      redirect_to root_url
    else
      flash[:danger] = "投稿に失敗しました。"
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

    private

      def post_params
        params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
      end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc ).paginate(page: params[:page], per_page: 5)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partial/navbar" if current_user %>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/create.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render "posts/like", post: @post) %>'

app/views/likes/destroy.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render "posts/like", post: @post) %>'

app/views/partial/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <%= link_to "タイトル", root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse justify-content-end">
        <ul class="navbar-nav">
          <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'nav-link' %>
          <%= link_to "投稿" , new_post_path, class: 'nav-link' %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/posts/_like.html.erb
<% if current_user.liked_by(post.id).present? %>    
  <%= link_to post_like_path(post, current_user.liked_by(post.id)), class: "like-link", method: :delete, remote: true do %>
    <i class="fas fa-heart fa-lg like-color"></i>
  <% end %>
  <%= post.likes.count %>
<% else %>
  <%= link_to post_likes_path(post), class: "like-link", method: :post, remote: true do %>
    <i class="far fa-heart fa-lg unlike-color"></i>
  <% end %>
  <%= post.likes.count %>
<% end %>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <div class="mt-4 card">
      <h2 class="card-header text-center">投稿</h2>
      <div class="card-body">
        <%= form_with(model: @post, local: true) do |f| %>
          <%= f.fields_for :photos do |i| %>
            <%= i.file_field :image %>
          <% end %>
          <div class="mt-3">
            <%= f.text_area :caption, class: "form-control", placeholder: "説明を書く" %>
          </div>
          <div class="mt-3 text-center">
            <%= f.submit "投稿", class: "btn btn-primary form-control" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <div class="card my-5">
      <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
      
      <small class="ms-2 mt-2 text-muted sm"><%= time_ago_in_words(@post.created_at).upcase %>前</small>
      
      <div id="post_<%= @post.id %>">
        <%= render "like", post: @post %>
      </div>

      <hr>

      <div class="card-body">
        <%= @post.caption %>
      </div>
    </div>
  </div>
</div>

app/views/tops/index.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1">
    <div class="row mt-4">
      <% @posts.each do |post| %>
        <div class="col-sm-4">
          <div class="card">
            <%= link_to post_path(post) do %>
              <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
            <% end %>
            <div id="post_<%= post.id %>">
              <%= render "posts/like", post: post %>
            </div>

            <div class="card-body">
              <%= post.caption %>
            </div>
          </div>
        </div>
      <% end %>

      <%= will_paginate @posts, :previous_label => ' &lt 前へ |', :next_label => '| 次へ &gt' %>
    </div>
  </div>
</div>